sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t amazing-app -f Dockerfile.dev .

script:
  - docker run -e CI=true amazing-app npm run test
 
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Test-Amazing-App"
  env: "Test-Amazing-App-env"
  bucket_name: "elasticbeanstalk-eu-north-1-152850554113"
  bucket_path: "Test-Amazing-App"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY