FROM node:16-alpine

USER node
 
#RUN mkdir -p /home/node/appWORKDIR /home/node/app 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# https://www.geeksforgeeks.org/chown-command-in-linux-with-examples/
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

# Default command
CMD ["npm", "run", "dev"]